language: erlang
otp_release:
  - 18.1
install:
  - make
  - ./rebar3 update
script:
  - make eunit
  - make xref
  - make ct
  - make peer-to-peer-ad-counter-simulation
  - make client-server-ad-counter-simulation
  - make peer-to-peer-game-tournament-simulation
  - make client-server-game-tournament-simulation
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: required
env:
  global:
    - OMIT_HIGH_ULIMIT=true
